# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mesh_pb2 as mesh__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeshServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/ciel.mesh.MeshService/Ping',
                request_serializer=mesh__pb2.PingRequest.SerializeToString,
                response_deserializer=mesh__pb2.PongResponse.FromString,
                _registered_method=True)
        self.Announce = channel.unary_unary(
                '/ciel.mesh.MeshService/Announce',
                request_serializer=mesh__pb2.AnnounceRequest.SerializeToString,
                response_deserializer=mesh__pb2.AnnounceResponse.FromString,
                _registered_method=True)
        self.FindPeer = channel.unary_unary(
                '/ciel.mesh.MeshService/FindPeer',
                request_serializer=mesh__pb2.FindPeerRequest.SerializeToString,
                response_deserializer=mesh__pb2.FindPeerResponse.FromString,
                _registered_method=True)
        self.Gossip = channel.unary_unary(
                '/ciel.mesh.MeshService/Gossip',
                request_serializer=mesh__pb2.GossipMessage.SerializeToString,
                response_deserializer=mesh__pb2.GossipAck.FromString,
                _registered_method=True)
        self.RequestVote = channel.unary_unary(
                '/ciel.mesh.MeshService/RequestVote',
                request_serializer=mesh__pb2.RequestVoteRequest.SerializeToString,
                response_deserializer=mesh__pb2.RequestVoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/ciel.mesh.MeshService/AppendEntries',
                request_serializer=mesh__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=mesh__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)
        self.PBFTPrePrepare = channel.unary_unary(
                '/ciel.mesh.MeshService/PBFTPrePrepare',
                request_serializer=mesh__pb2.PBFTMessage.SerializeToString,
                response_deserializer=mesh__pb2.PBFTResponse.FromString,
                _registered_method=True)
        self.PBFTPrepare = channel.unary_unary(
                '/ciel.mesh.MeshService/PBFTPrepare',
                request_serializer=mesh__pb2.PBFTMessage.SerializeToString,
                response_deserializer=mesh__pb2.PBFTResponse.FromString,
                _registered_method=True)
        self.PBFTCommit = channel.unary_unary(
                '/ciel.mesh.MeshService/PBFTCommit',
                request_serializer=mesh__pb2.PBFTMessage.SerializeToString,
                response_deserializer=mesh__pb2.PBFTResponse.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/ciel.mesh.MeshService/SyncState',
                request_serializer=mesh__pb2.SyncRequest.SerializeToString,
                response_deserializer=mesh__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.StreamMessages = channel.stream_stream(
                '/ciel.mesh.MeshService/StreamMessages',
                request_serializer=mesh__pb2.MeshEnvelope.SerializeToString,
                response_deserializer=mesh__pb2.MeshEnvelope.FromString,
                _registered_method=True)


class MeshServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Discovery & Heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Announce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Gossip(self, request, context):
        """Gossip
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """Raft Consensus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PBFTPrePrepare(self, request, context):
        """PBFT Consensus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PBFTPrepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PBFTCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Data Sync
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=mesh__pb2.PingRequest.FromString,
                    response_serializer=mesh__pb2.PongResponse.SerializeToString,
            ),
            'Announce': grpc.unary_unary_rpc_method_handler(
                    servicer.Announce,
                    request_deserializer=mesh__pb2.AnnounceRequest.FromString,
                    response_serializer=mesh__pb2.AnnounceResponse.SerializeToString,
            ),
            'FindPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPeer,
                    request_deserializer=mesh__pb2.FindPeerRequest.FromString,
                    response_serializer=mesh__pb2.FindPeerResponse.SerializeToString,
            ),
            'Gossip': grpc.unary_unary_rpc_method_handler(
                    servicer.Gossip,
                    request_deserializer=mesh__pb2.GossipMessage.FromString,
                    response_serializer=mesh__pb2.GossipAck.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=mesh__pb2.RequestVoteRequest.FromString,
                    response_serializer=mesh__pb2.RequestVoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=mesh__pb2.AppendEntriesRequest.FromString,
                    response_serializer=mesh__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'PBFTPrePrepare': grpc.unary_unary_rpc_method_handler(
                    servicer.PBFTPrePrepare,
                    request_deserializer=mesh__pb2.PBFTMessage.FromString,
                    response_serializer=mesh__pb2.PBFTResponse.SerializeToString,
            ),
            'PBFTPrepare': grpc.unary_unary_rpc_method_handler(
                    servicer.PBFTPrepare,
                    request_deserializer=mesh__pb2.PBFTMessage.FromString,
                    response_serializer=mesh__pb2.PBFTResponse.SerializeToString,
            ),
            'PBFTCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.PBFTCommit,
                    request_deserializer=mesh__pb2.PBFTMessage.FromString,
                    response_serializer=mesh__pb2.PBFTResponse.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=mesh__pb2.SyncRequest.FromString,
                    response_serializer=mesh__pb2.SyncResponse.SerializeToString,
            ),
            'StreamMessages': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=mesh__pb2.MeshEnvelope.FromString,
                    response_serializer=mesh__pb2.MeshEnvelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ciel.mesh.MeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ciel.mesh.MeshService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/Ping',
            mesh__pb2.PingRequest.SerializeToString,
            mesh__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/Announce',
            mesh__pb2.AnnounceRequest.SerializeToString,
            mesh__pb2.AnnounceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/FindPeer',
            mesh__pb2.FindPeerRequest.SerializeToString,
            mesh__pb2.FindPeerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Gossip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/Gossip',
            mesh__pb2.GossipMessage.SerializeToString,
            mesh__pb2.GossipAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/RequestVote',
            mesh__pb2.RequestVoteRequest.SerializeToString,
            mesh__pb2.RequestVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/AppendEntries',
            mesh__pb2.AppendEntriesRequest.SerializeToString,
            mesh__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PBFTPrePrepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/PBFTPrePrepare',
            mesh__pb2.PBFTMessage.SerializeToString,
            mesh__pb2.PBFTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PBFTPrepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/PBFTPrepare',
            mesh__pb2.PBFTMessage.SerializeToString,
            mesh__pb2.PBFTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PBFTCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/PBFTCommit',
            mesh__pb2.PBFTMessage.SerializeToString,
            mesh__pb2.PBFTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ciel.mesh.MeshService/SyncState',
            mesh__pb2.SyncRequest.SerializeToString,
            mesh__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ciel.mesh.MeshService/StreamMessages',
            mesh__pb2.MeshEnvelope.SerializeToString,
            mesh__pb2.MeshEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
